# Generated by Django 6.0.2 on 2026-03-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='email')),
                ('role', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
